### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by JIElite** [Lee-W/NCKU_Grade#1]
Hello, 
There are something wrong when I follow your instruction and clone this repo:

jielite@RailGun-X230:~$ **git clone --recursive https://github.com/Lee-W/NCKU_Grade.git**
Cloning into 'NCKU_Grade'...
remote: Counting objects: 105, done.
remote: Total 105 (delta 0), reused 0 (delta 0), pack-reused 105
Receiving objects: 100% (105/105), 45.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (50/50), done.
Checking connectivity... done.
Submodule 'HTML_Form_Parser' (https://github.com/Lee-W/HTML_Form_Parser) registered for path 'HTML_Form_Parser'
Cloning into 'HTML_Form_Parser'...
remote: Counting objects: 33, done.
remote: Total 33 (delta 0), reused 0 (delta 0), pack-reused 33
Unpacking objects: 100% (33/33), done.
Checking connectivity... done.
**fatal: reference is not a tree: 67e2f21ce77166675dbfe7e97ff28528c31b34bb
Unable to checkout '67e2f21ce77166675dbfe7e97ff28528c31b34bb' in submodule path 'HTML_Form_Parser'**

**Comment by Lee-W** [comment]
This error is due to HTML_Form_Parser renaming.
I remove the dependency of that lib in the new version of NCKU Grade.
